name: Build apex
run-name: Build apex website

on:
  workflow_call:

env:
  RUNTIME: node@26

jobs:
  build-apex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v3
        with:
          runtime: ${{ env.RUNTIME }}
      - run: pnpm build
        working-directory: apex
      - run: zip -qr ../../apex.zip .
        working-directory: apex/dist
      - uses: actions/upload-artifact@v7
        with:
          name: apex.zip
          path: apex.zip
