name: CI
run-name: CI deploy to dev env

on:
  push:
    branches: ['main']

jobs:
  verify:
    uses: ./.github/workflows/verify.yml

  deploy:
    needs: verify
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/deploy.yml
    with:
      cloudflare_env: dev
      dev_build: true
    secrets: inherit
