name: App UI CI

on:
  push:
    branches: [ main ]
    paths:
      - 'ui/**/*'
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - build
      - check
      - lint
      - test
      - playwright
    steps:
      - run: echo "When you're on a holiday"

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: |
          cd ui
          pnpm i
          pnpm build

  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: |
          cd ui
          pnpm i
          pnpm check

  playwright:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: |
          cd ui
          pnpm i
          npx playwright install
          npx playwright test

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: |
          cd ui
          pnpm i
          npx vitest run

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - run: |
          cd ui
          pnpm i
          npx eslint .

  publish-prerelease:
    name: Publish @next to npm
    needs: verified
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Build package
        working-directory: ui
        run: |
          pnpm i
          pnpm build
          pnpm package
      - name: Increment version
        id: semver
        working-directory: ui
        run: echo "version=$(npm version prerelease --no-git-tag-version | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"
      - name: Publish prerelease
        working-directory: ui
        run: npm publish --public --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Bump ver > git
        run: |
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
          git commit -am "increment @eighty4/app-ui@next to ${{steps.semver.outputs.version}}"
          git push
    outputs:
      version: ${{steps.semver.outputs.version}}
