name: Verify
run-name: "Verify ${{ github.sha }} (${{ github.ref_name }})"

on:
  pull_request:
    branches: [ '*' ]
  workflow_call:

env:
  flutter_version: 3.27.1

jobs:

  verify:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo "41°00′19″N 122°59′51″W"

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apex
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: apex/node_modules
          key: dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - run: pnpm i
      - run: pnpm build
      - run: (cd dist && zip -qr ../www.zip .)
      - uses: actions/upload-artifact@v4
        with:
          name: www.zip
          path: apex/www.zip
