name: Verify
run-name: 'Verify ${{ github.sha }} (${{ github.ref_name }})'

on:
  pull_request:
    branches: ['*']
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    needs:
      - build
      - fmtcheck
    steps:
      - run: echo "41°00′19″N 122°59′51″W"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - uses: pnpm/action-setup@v4
      - run: pnpm i
      - run: pnpm build
      - run: (cd dist && zip -qr ../www.zip .)
      - uses: actions/upload-artifact@v4
        with:
          name: www.zip
          path: www.zip

  fmtcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - uses: pnpm/action-setup@v4
      - run: pnpm i
      - run: pnpm fmtcheck
